### ISSUE TITLE
Composer support?

### ISSUE THREAD

**Issue by milosmoto** [Ziggeo/ZiggeoPhpSdk#18]
Questions:
1)Hi guys, is there a composer require support, so we can pull this sdk via composer and autoload this sdk on a framework?

2)I need to get public video url so I can export that link to my customers, is that what I will get from this method:
$ziggeo->videos()->get($token_or_key) 

3) What is private_key and encryption here:
$ziggeo = new Ziggeo('*token*', '*private_key*', '*encryption_key*'); 
I have only APPLICATION_TOKEN for API connection?

cc @Bane-D @oliverfriedmann

**Comment by Bane-D** [comment]
Hi Milos,

> Hi guys, is there a composer require support, so we can pull this sdk via composer and autoload this sdk on a framework?

I believe that you are looking for this: https://packagist.org/packages/ziggeo/ziggeophpsdk

> I need to get public video url so I can export that link to my customers, is that what I will get from this method:
> $ziggeo->videos()->get($token_or_key)

Quick reply would be yes, however it might depend on what you want to have it as. We have "public video URL" phrase for the URLs that are just video tokens behind a specific URL. This is something that must be enabled in your account first and is easy to build, as demonstrated with the following:

`url = "https://ziggeo.io/v/" + {VIDEO_TOKEN}`

> What is private_key and encryption here:
> $ziggeo = new Ziggeo('token', 'private_key', 'encryption_key');
> I have only APPLICATION_TOKEN for API connection?

All applications have all 3 tokens and keys. They are used to precisely determine that it is actually the owner of the application. You can find all of them in the Overview page of each of your application.

To find it:
1. log into your Ziggeo account
2. click on the application that you would like to grab the keys for
3. click on "Overview" page

That is it :)

Hope this helps.

Regards,
Bane

**Comment by milosmoto** [comment]
@Bane-D  Thanks it was super helpful.

In that case if I can build link to the video for my customers all I need is:
url = "https://ziggeo.io/v/" + {VIDEO_TOKEN}

How I can enable that on my account?

Thanks

**Comment by Bane-D** [comment]
Hi Milos,

Glad to hear it.

Will close it however if you have any other questions please do let us know :)

Regards,
Bane
