### ISSUE TITLE
Duration not working

### ISSUE THREAD

**Issue by palash14** [Ziggeo/ZiggeoPhpSdk#29]
Hi,

Now I'm facing a new issue, the current code does not return duration while uploading a large video file.

Please let me know how to fix this.

Thanks
Palash

**Comment by Bane-D** [comment]
Hi Palash,

I am sorry for silence from our side. I actually thought that I had replied back and wanted to re-check in with you now.

Can you please tell me if you are still facing the same issue? Also if I am understanding you correctly, when the upload is finished you do not have the length of the video available.

I am guessing that if you were to use webhooks to get notification once the video has been transcoded then it would be available.

For reference: https://github.com/Ziggeo/ZiggeoPhpSdk/blob/master/demos/_webhook_for_video_ready.php

Best,
Bane

**Comment by palash14** [comment]
Hi Bane,

Thanks for help.

I have fixed the issue by webhooks.

Thanks
Palash
