### ISSUE TITLE
Protect the video link

### ISSUE THREAD

**Issue by palash14** [Ziggeo/ZiggeoPhpSdk#30]
Hi,

How can I protect the video so the user can not copy or paste the video link for example if we are using s3 bucket and AWS have option for temporary URL so that link can expire in 30 min but in your system how do we can set using js SDK, I found that if I set auth: true, then it generates a link but if you smart enough you can remove those query and I can still get the video link.

So tell me how to stop this,

Thanks

**Comment by bansal84k** [comment]
Hi Palash,

I believe we are already communicating about this one on Zendesk, will go ahead and close it here to keep the communication focused through one medium.

Regards
Karan
