### ISSUE TITLE
Unable to install using Composer version 2.0.8 and Laravel 8

### ISSUE THREAD

**Issue by kumogire** [Ziggeo/ZiggeoPhpSdk#33]
This is what I get when I run composer install for the Ziggeo PHPSDK:

Generating optimized autoload files
Class ZiggeoAuth located in ./vendor/ziggeo/ziggeophpsdk/classes/ZiggeoAuth.php does not comply with psr-0 autoloading standard. Skipping.
Class ZiggeoAnalytics located in ./vendor/ziggeo/ziggeophpsdk/classes/ZiggeoAnalytics.php does not comply with psr-0 autoloading standard. Skipping.
Class ZiggeoEffectProfiles located in ./vendor/ziggeo/ziggeophpsdk/classes/ZiggeoEffectProfiles.php does not comply with psr-0 autoloading standard. Skipping.
Class ZiggeoAuthtokens located in ./vendor/ziggeo/ziggeophpsdk/classes/ZiggeoAuthtokens.php does not comply with psr-0 autoloading standard. Skipping.
Class ZiggeoStreams located in ./vendor/ziggeo/ziggeophpsdk/classes/ZiggeoStreams.php does not comply with psr-0 autoloading standard. Skipping.
Class ZiggeoEffectProfileProcess located in ./vendor/ziggeo/ziggeophpsdk/classes/ZiggeoEffectProfileProcess.php does not comply with psr-0 autoloading standard. Skipping.
Class ZiggeoConnect located in ./vendor/ziggeo/ziggeophpsdk/classes/ZiggeoConnect.php does not comply with psr-0 autoloading standard. Skipping.
Class ZiggeoMetaProfileProcess located in ./vendor/ziggeo/ziggeophpsdk/classes/ZiggeoMetaProfileProcess.php does not comply with psr-0 autoloading standard. Skipping.
Class ZiggeoMetaProfiles located in ./vendor/ziggeo/ziggeophpsdk/classes/ZiggeoMetaProfiles.php does not comply with psr-0 autoloading standard. Skipping.
Class ZiggeoWebhooks located in ./vendor/ziggeo/ziggeophpsdk/classes/ZiggeoWebhooks.php does not comply with psr-0 autoloading standard. Skipping.
Class ZiggeoApplication located in ./vendor/ziggeo/ziggeophpsdk/classes/ZiggeoApplication.php does not comply with psr-0 autoloading standard. Skipping.
Class ZiggeoException located in ./vendor/ziggeo/ziggeophpsdk/classes/ZiggeoException.php does not comply with psr-0 autoloading standard. Skipping.
Class ZiggeoVideos located in ./vendor/ziggeo/ziggeophpsdk/classes/ZiggeoVideos.php does not comply with psr-0 autoloading standard. Skipping.
Class ZiggeoConfig located in ./vendor/ziggeo/ziggeophpsdk/classes/ZiggeoConfig.php does not comply with psr-0 autoloading standard. Skipping.

Is there a way to easily correct this?

**Comment by Bane-D** [comment]
Hi Keith,

I have just done the following steps (see bellow) and could not recreate any issues.

```
git clone https://github.com/Ziggeo/ZiggeoPhpSdk.git
```
Then I installed Composer into the directory (https://getcomposer.org/download/)
```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
./composer.phar install
```
For this I got:
> Installing dependencies from lock file (including require-dev)
> Verifying lock file contents can be installed on current platform.
> Package operations: 1 install, 0 updates, 0 removals
>  - Downloading phpseclib/phpseclib (2.0.31)
>  - Installing phpseclib/phpseclib (2.0.31): Extracting archive
> Generating autoload files
> 1 package you are using is looking for funding.
> Use the `composer fund` command to find out more!

I have checked the version and this is what I got:
> ./composer.phar --version
> Composer version 2.1.5 2021-07-23 10:35:47

Can you tell us what version of composer you are running? Also is it global install or local like the above?

It is also a bit strange that it is complaining about [psr-0](https://www.php-fig.org/psr/psr-0/) since current version is [psr-4](https://www.php-fig.org/psr/psr-4/).
